# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Generate and Deploy

on:
  workflow_call:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install lxml
    - name: Configure NPM
      working-directory: npm
      run: |
        echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" >> .npmrc
        echo "always-auth: true" >> .npmrc
    - name: Install NPM Dependencies
      run: |
        cd npm
        npm install
    - name: Run Generate
      run: python generate.py
    - name: Bump Version
      run: |
        cd npm
        npm version patch
    - name: Build the NPM Package
      run: |
        cd npm
        npm run rollup
    - uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: 'npm/package.json'
        provenance: true
    - name: Commit new version back to github
      uses: EndBug/add-and-commit@v9
      with:
        add: 'npm/package.json'
        committer_name: GitHub actions
        committer_email: actions@github.com
        message: 'npm version update'
        push: true


